apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: vault-enrollment-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-serviceaccounts
subjects:
- kind: ServiceAccount
  namespace: vault
  name: vault-enrollment-controller
